### ISSUE TITLE
Bug with the automation 

### ISSUE THREAD

**Issue by HeavyTobi** [fabianbees/breitbandmessung-docker#10]
I‘m having one weird issue with the docker container: 

I used touch /RUN to create the file to activate the automation. It didn’t work for some reason. Then I saw in the logs that it should also be possible by using the clipboard function of the container but then I noticed a weird thing in the logs:

`RUN not set in clipboard or file /RUN not available. (value in clipboard is RUN)
`
Am I doing it wrong or is that some bug in the script which only I have? 

one other weird thing is that it worked fine yesterday, saying something like `trying to start speedtest`

**Comment by fabianbees** [comment]
> I used touch /RUN to create the file to activate the automation. It didn’t work for some reason. 

Normally this should work without issues, i will take a look at it again, when i have time.


> Then I saw in the logs that it should also be possible by using the clipboard function of the container

This feature is currently not yet fully implemented and functional, and thus also not mentioned in the documentation.
(At this point it should not be used.)

**Comment by LizenzFass78851** [comment]
I also tested with `touch /RUN ` command on the docker container and it worked for me without any problems. The speed test was started and the second test, which should be started after 5 minutes, was also started successfully.

So the script recognizes the /RUN file without any problems and starts running.

-----

the following error message on the log:
`RUN not set in clipboard or file /RUN not available. (value in clipboard is RUN)`

This is because the following line is excluded or not included in the script runtime:
https://github.com/fabianbees/breitbandmessung-docker/blob/ae39bdc4eaf69c74824efdeb04323934f5e9f24e/run-speedtest.sh#L14-L17

if it is intentional because: 
> This feature is currently not yet fully implemented and functional, and thus also not mentioned in the documentation.

**Comment by HeavyTobi** [comment]
just pulled the latest image, now it works fine, also with the clipboard method. Thanks
