### ISSUE TITLE
Not starting due to tcurrent time outside of the specified range, although it is inside

### ISSUE THREAD

**Issue by buchbergerd** [fabianbees/breitbandmessung-docker#25]
Thanks for creating this container! I am using it with Portainer.
Unfortunately, it seems not to work and the log does not make sense for me:

```
[speedtest   ] Run set!
[speedtest   ] Current time is 10:57:29
[speedtest   ] NOT STARTING. The current time is outside the specified range of 07:30 and 21:00.
```

The current time clearly is insode the (default) range. Logging into the container and using `date` gives the right time, too.
Could you please fix that?

**Comment by fabianbees** [comment]
Hi, thanks for your bug report.

This issue should be fixed in the latest version with commit #[8da8ba5](https://github.com/fabianbees/breitbandmessung-docker/commit/8da8ba53aeda9027c69c7813d5e2ec11bde50034).

I have recently changed the measurement window to only measure between 13:00 till 22:30 o' clock, since the network load in this timewindow is generally higher and therefore bottlenecks can be better observered (especially with shared media access technology like DOCSIS cable internet connections.)

The issue you have reported was simply an oversight with the Log output.
